language: objective-c
osx_image: xcode10

install:
  - brew install swiftlint

env:
  global:
    - WORKSPACE=RidiOAuth2.xcodeproj/project.xcworkspace

matrix:
  include:
    - env: DESTINATION="arch=x86_64" SCHEME=macOS SDK="macosx"
    - env: DESTINATION="platform=iOS Simulator,name=iPhone 7,OS=11.4" SCHEME=iOS SDK="iphonesimulator"

script:
  - swiftlint
  - xcodebuild -workspace $WORKSPACE -scheme RidiOAuth2Tests-$SCHEME -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c

notifications:
  email: false
  slack:
    rooms:
      - 'KPzZCLZX8QH84rkd6VmpqEqLLE/U78X/UqWC+8d652rxToRf6q2gM3A84hu2/sZ8wVsDc7vbW609qpb/m/LyCuz/i5SsaBjllk4GhX8I7xLuyqkrN7nTX8DJwo7Grj+krfwlWyRrLiK8gpUbydR7tEMMRMaQVPdV6u0iLn5LGxvXV7HUUtjB0verLx3/q1gQHqzdegreZ8TISVtJzr/DY4sRyx25S5Aec1xo0664ozxdHLDLjZQ5FmwWo8yTRaE33q9Nh2yfMVcshvzhuSVC2Lv2gf6/oEMzMmkvpx+ZOUZjB73f0x/bkIEzaGhU9XUy4TVtHcxyzlf8iIuNPrz8lAALZb4CA0rdhpemRDjtrc13OE7r2EamcDrH8CWavzz6vZpEiug1KG2sFy55BhWBrem/MN4gNoFVNO+AhqlzC0Xsk0R8yPTSbmTvLMVbVhG3B1JWzQbX7j6lC6U6G92RbB9djKepkJT4/QhBJBukQRYW5n4rlChZJYvwfbnzCYIeHl11ZDjR70LpJWoAQSiEVNebFrDbrktsRaib0Eh6yeB+Ww1KTE1hqfM3X1qQMysFqk0hatjK/8OX8t7HYPi865udpX/Zp9RU2/aU1lCFUni7rGkV81Xkyz+GvNIzeM/h0l+NIZ1RVIgpRzeEjTqczabJZ75YgSGzdiKnP7ZhrCs='
    on_success: change
