language: objective-c
osx_image: xcode10

env:
  global:
    - WORKSPACE=RidiOAuth2.xcodeproj/project.xcworkspace

matrix:
  include:
    - env: DESTINATION="arch=x86_64" SCHEME=macOS SDK="macosx"
    - env: DESTINATION="platform=iOS Simulator,name=iPhone 7,OS=11.4" SCHEME=iOS SDK="iphonesimulator"

script:
  - xcodebuild -workspace $WORKSPACE -scheme RidiOAuth2Tests-$SCHEME -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c

notifications:
  email: false
  slack:
    rooms:
      secure: XlCie8Jy4uOSBQczA1z0Qu4lIgOPnmhjnT7NwWLx9A7y3vFylMHLgtHyt0dqN7YbGZG0dETQSzGkQ7ZwD27jeQfUgGoy7pj54HIhIHVWa5b1uRL0xURd7dk9qAj8ciYybAICGpj6Q8DBdi9Wdj3hytuDNECbk35f5BwcNP+BUcSMoDQhRMmwgPy+JqNUcGERBOUgCGlTvhRFPRiHyAlMbNDT8VEYPOWgBZafMej1x3MAhHA9fN4geuO71eu7ZYuzxfZWQhWoiUWH0ro4NhMpE3NbVxbT/ZXgWyO3oIUncxN0o7LOrF3rdD7GF7pYN8thMfbXOroHPtMulMDpzpGastIRNoNbJb+CibjKscizYaw5Ypw+lZPa10J8LtkJSxh6NkvOIuuiSeGJwKQnvtLgSQeTSwtpfxFRGfgqIcahJUkGND2iEjGFfI1VZYz9gNpoLLxiOduNAmLE7bDMNSsqxmLpJlaoiDwEViEv8Dpn0d3YHnZdbmtyHZhgxU5VQmJNU9JfUy4B5rLIxA2fICUz+1NeV/bTiZ1oBynBVXMOZHYuFS3KLUPG1rU71f4jPJgIWlEyjhY1Fpwr3D/azZQv8odAn7x4TruB585umeY9/wekWCf151V/AYnZNGAiVmaV4MAsSBtZuGtvz+EpnJZlsODSbB8/eAoHcc8mgGIp+po=
    on_success: change
