language: objective-c
osx_image: xcode11.3

install:
  - brew install swiftlint

matrix:
  include:
    - env: DESTINATION="arch=x86_64" SCHEME=macOS SDK="macosx"
    - env: DESTINATION="platform=iOS Simulator,name=iPhone 7,OS=11.4" SCHEME=iOS SDK="iphonesimulator"

script:
  - swiftlint
  - swift package generate-xcodeproj
  - xcodebuild -scheme RidiOAuth2-Package -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c

notifications:
  email: false
  slack:
    rooms:
      secure: OHvqdkEI50NuEjPifHxcoMvIKzEifX5dRWQ/ukEZvyfndgH5Cy3yGp/lo0lg8bH+WUI0UzX5FpXPS1AQvr+VR6HHKTwLHnajy+K/DZOwAnwR6oPb6m95TlGi6a6x+QKYSmf5sO36xqDT76t+c607qA8lcwGoE0HQIrnkGmCPRVutryRIu0lLUZflSI/F6S4npRLhkiQ+lDgwGhdL4QSqeh2W84hyPkdX2p8K2xV4VBlJWSTj5s0x+Dfxxokp2C9k9Nl4ZtTQHmth84jNFdp6idIUtofD5X8k/zr9jFiFQOLIDXP2jdRPp8chia6SnkUDYRfUoH6sAxQE26DdzPQgprtGbKFWi1TxOxhFneUWOhE8dv2BCfk93kUM69q065YvNLIcj4f7FzJhFPlA9B0WwgOYtO8flX8+NQDY378WcU1WdmYbgdHorOPB//slBCooFGnvjbp1TR74lvlYQiPqVmfkEpQoAbxwS8+8uR2SVQWbQnHGg1JBX80r6xs8woYBC64U5hJaclecDS7fd35EbPa6IP+3SgVwe0o56BCGydr74ZsMJ3oMuuFxMbhQ8MenY9AbydlT4fFrrZC10IFuJodU2WB1T7IKyecR2B2kawjnzZRN/vofcKuu6oyozhI2b0J4K1nSSG43qYb5AzWne4DmFCGOZM39pyLpe1H7lJ0=
    on_success: change
