language: objective-c
osx_image: xcode11.5

install:
  - brew install swiftlint

matrix:
  include:
    - env: DESTINATION="arch=x86_64" SCHEME=macOS SDK="macosx"
    - env: DESTINATION="platform=iOS Simulator,name=iPhone 7,OS=11.4" SCHEME=iOS SDK="iphonesimulator"

script:
  - swiftlint
  - swift package generate-xcodeproj
  - xcodebuild -scheme RidiOAuth2-Package -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c

notifications:
  email: false
  slack:
    rooms:
      secure: 'CVzbIsEAUByEfxC+aXuvOPc8L/VGrFdpnZ8zRNIlk+6SK/GN/tGGy+T1dfm0pQ+6MRyeELeHEOhQZ6yyrjhuQVlm4QNAs5NifVIM0Ps9QL095u3KMDaoCR388JfFUsb+BDVK/9Ko+Co/b/JsIARmdGLTk8fn9pa1sEg1HZ79aNssgdNFk4P3qtwwACZIG5JVQFgzEm82tKUK1PAfNWhoXeM52cF+xzZkAtXiMAXB4k98phQdcR6z7CPiKtUmdsyPJoFlHHwcNWhy0o1afYyXm0wAwi6kc2E45gAI/lG0GBwvStNvvdR6/nZ0Pnw38VmWdtg9lA96uShMH7gpLCGQylMd094zRvI2qAQXey+gCQRsQYPm/QjLMObHgg38YJaUPh4Ar8qJUSHTJWwDLAEck9PGuxBHE8/jj56wDJ+cNDvWGmNBBRA+gHlSwEafR1+61PguFnhGDFflLwVezariwJkceiRkMLCTfjXcUL7skL+A1bXEJOgL1Euw9zRRKx4uR8DanLY45ZbijsQ97AVTGsE4n9cAl2VRw2WlzF3THdr3oFqav5gfOKfl/uQtBwrw+SsvO7C6Jq+8Go+TYUmjfBrPKjbJPW3wW6OAUOuSGoQNG4cENUr85lqUR1sH6i/Y1qFbUICqfDeeQGogy69eedd9QGMut6CGtAut7XxkSSo='
    on_success: change
