use_frameworks!

target 'RidiOAuth2-Demo-iOS' do
    platform :ios, '9.0'
    pod 'RidiOAuth2', :path => '../'
end

target 'RidiOAuth2-Demo-macOS' do
    platform :osx, '10.10'
    pod 'RidiOAuth2', :path => '../'
end

target 'RidiOAuth2-Demo-tvOS' do
    platform :tvos, '9.0'
    pod 'RidiOAuth2', :path => '../'
end
