use_frameworks!

def pods
    pod 'RidiOAuth2', :path => '../'
    pod 'JWTDecode'
end

target 'RidiOAuth2-Demo-iOS' do
    platform :ios, '9.0'
    pods
end

target 'RidiOAuth2-Demo-macOS' do
    platform :osx, '10.10'
    pods
end
