use_frameworks!

target 'ridi-oauth2-demo-ios' do
    platform :ios, '9.0'
    pod 'ridi-oauth2', :path => '../'
end

target 'ridi-oauth2-demo-macos' do
    platform :osx, '10.10'
    pod 'ridi-oauth2', :path => '../'
end

target 'ridi-oauth2-demo-tvos' do
    platform :tvos, '9.0'
    pod 'ridi-oauth2', :path => '../'
end
